export const DEFAULT_MIN_DISTANCE = 80;
export const DEFAULT_MIN_DISTANCE_SQUARED =
  DEFAULT_MIN_DISTANCE * DEFAULT_MIN_DISTANCE;

export const LARGE_RADIUS = 5;
export const LARGE_RADIUS_SQUARED = LARGE_RADIUS * LARGE_RADIUS;
export const LARGE_DIAMETER = LARGE_RADIUS * 2;
export const LARGE_DIAMETER_SQUARED = LARGE_DIAMETER * LARGE_DIAMETER;

export const SMALL_RADIUS = 3;
export const SMALL_RADIUS_SQUARED = SMALL_RADIUS * SMALL_RADIUS;
export const SMALL_DIAMETER = SMALL_RADIUS * 2;
export const SMALL_DIAMETER_SQUARED = SMALL_DIAMETER * SMALL_DIAMETER;

export const LARGE_MASS = 3;
export const SMALL_MASS = 2;
